### ISSUE TITLE
is it possible to use zProperties of device in CustomOverview?

### ISSUE THREAD

**Issue by argaliev** [cluther/ZenPacks.example.CustomOverview#1]
is it possible to use zProperties of device in CustomOverview?

**Comment by cluther** [comment]
@argaliev: Yes, I think that should work fine. You wouldn't need to add the new property into the `__init__.py`, you would just reference the zProperty's _name_ as in zSnmpCommunity in the JavaScript.

**Comment by argaliev** [comment]
after testing, has no luck. I am using code:

`Ext.onReady(function() {
    var DEVICE_OVERVIEW_ID = 'deviceoverviewpanel_summary';
    Ext.ComponentMgr.onAvailable(DEVICE_OVERVIEW_ID, function(){
        var overview = Ext.getCmp(DEVICE_OVERVIEW_ID);

        overview.addField({
            name: 'zSnmpVer',
            fieldLabel: _t('test_zproperty'),
        });
    });

});`

It works if using device property, but if use zProperty, field is empty. 
Zenoss version 4.2.5

**Comment by argaliev** [comment]
Jane Curry has created zenpack with example how to implement this:
[https://github.com/ZenossDevGuide/ZenPacks.community.DeviceOverviewMods](url)
